In [3]:
a=[0,1,6,4,3,0,8,9,0,5,0,0]
k=0
for i in range(len(a)):
    if(a[i]==0):
        a[k],a[i]=a[i],a[k]
        k+=1
a

[0, 0, 0, 0, 0, 1, 8, 9, 6, 5, 4, 3]

In [4]:
import numpy as np
arr=np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12],
              [13,14,15,16]])
arr[1:3,0:2]

array([[ 5,  6],
       [ 9, 10]])

In [5]:
arr[:,2:4]

array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [15, 16]])

In [6]:
import cv2 as cv
a=cv.imread("C:\\Users\\ompra\\OneDrive\\Pictures\\20180205_224458.jpg")
a.dtype

dtype('uint8')

In [7]:
import cv2 as cv
cap=cv.VideoCapture(0)
while(1):
    ret,frame=cap.read()
    cv.imshow("window",frame)
    if(cv.waitKey(1)==ord("q")):
        cv.imwrite("a.jpg",frame)
        break
cap.release()
cv.destroyAllWindows()
a=cv.imread("a.jpg")
a

array([[[ 9,  6,  8],
        [ 9,  6,  8],
        [10,  7,  9],
        ...,
        [22, 19, 21],
        [22, 19, 21],
        [22, 19, 21]],

       [[ 9,  6,  8],
        [ 9,  6,  8],
        [ 9,  6,  8],
        ...,
        [23, 20, 22],
        [23, 20, 22],
        [23, 20, 22]],

       [[ 9,  6,  8],
        [ 9,  6,  8],
        [ 9,  6,  8],
        ...,
        [26, 21, 23],
        [23, 20, 22],
        [22, 19, 21]],

       ...,

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        ...,
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        ...,
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        ...,
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]]], dtype=uint8)

    above code is for video capture and getting an image.

In [8]:
import cv2 as cv
cap=cv.VideoCapture(0)
while(1):
    ret,frame=cap.read()
    gray=cv.cvtColor(frame,cv.COLOR_BGR2GRAY)
    cv.imshow("GRAY",gray)
    cv.imshow("win",frame)
    if(cv.waitKey(1)==ord("q")):
        cv.imwrite("a.jpg",frame)
        break
cap.release()
cv.destroyAllWindows()

    above code is for video capture in gray scale and getting an image.